//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDataTableApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        public int CusomerID { get; set; }
        [Required(ErrorMessage = "Please input a CompanyName")]
        public string CompanyName { get; set; }
        [Required(ErrorMessage = "I'm Simeon, and you are?")]
        public string ContactName { get; set; }
        public string Title { get; set; }
        [Required(ErrorMessage = "We may have to deliver a package to your address")]
        public string Address { get; set; }
        [Required(ErrorMessage = "Let's see the beautiful sunrise in your city")]
        public string City { get; set; }
        [Required(ErrorMessage = "Let's visit your Country")]
        public string Country { get; set; }
        [Required(ErrorMessage = "It's good we give you a call?")]
        public string Phone { get; set; }
    }
}
